version: "3.8"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=admin123
      - DB_NAME=N2_BancoDados
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: N2_BancoDados
    ports:
      - "3306:3306"
